### ISSUE TITLE
Waku v2: Implement basic filter protocol epic

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#134]
Spiritual successor to original https://github.com/status-im/nim-waku/issues/100

Broken down into these issues:

- [x] https://github.com/status-im/nim-waku/issues/100
- [x] https://github.com/status-im/nim-waku/issues/124
- [ ] https://github.com/status-im/nim-waku/issues/129
- [x] https://github.com/status-im/nim-waku/issues/133
- [ ] https://github.com/status-im/nim-waku/issues/167

As well as spec:

- [x] https://github.com/vacp2p/specs/issues/171

**Comment by oskarth** [comment]
@decanus are you going to do the node API integration to make sure this actually works?

**Comment by decanus** [comment]
@oskarth I plan to work on node api integration today.

**Comment by oskarth** [comment]
@decanus here too, would be good if you updated these issues instead of me having to clean up.

Closing as done.
