### ISSUE TITLE
Implement EIP-1459 for basic node discovery

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#452]
# Problem

Currently there's no node discovery for Waku, but we instead use hardcoded static nodes.

# Solution

The most basic form of node discovery, as was previously investigated, is likely https://eips.ethereum.org/EIPS/eip-1459

See https://rfc.vac.dev/spec/6/#node-discovery and https://vac.dev/dns-based-discovery

Additionally, corresponding update in Waku v2 recommending the use of DNS based discovery (identical to Waku v1)

As a further enhancement, we can look into using Discovery v5 module like Nimbus, but this isn't initially needed.

cc @jm-clius fyi on practical next steps re discovery once we think this is a priority

---
**_UPDATE 2021-06-14:_**
# Subtasks:

- [x] https://github.com/vacp2p/rfc/issues/398: Create `raw` specification
- [x] https://github.com/status-im/nim-waku/issues/615: DNS Resolver
- [x] https://github.com/status-im/nim-waku/issues/616: Merkle tree
- [x] https://github.com/status-im/nim-waku/issues/617: Client implementation
