### ISSUE TITLE
`chat2` improvements to support dogfooding

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#569]
### Problem

Now that a [`bridge`](https://github.com/status-im/nim-waku/issues/404) to Matterbridge/Discord has been deployed, we are ready for proper [Waku v2 dogfooding](https://github.com/status-im/nim-waku/issues/399) with the #waku Discord channel being set to read-only. This will be useful for the [upcoming testnet](https://github.com/status-im/nim-waku/issues/555
) as well.

The following improvements to the `chat2` app is necessary:
- [x] choose a more idiomatic content topic. The content topic is currently "dingpu". It should follow the notion of namespacing that is not fully specified yet, but used elsewhere in any case, most likely `/waku/2/default-content/proto`.
- [x] point to `prod` fleet by default, rather than `test`
- [x] enable `STORE` protocol by default

### Linked issues
https://github.com/status-im/nim-waku/issues/399
https://github.com/status-im/nim-waku/issues/555

**Comment by oskarth** [comment]
New testnet name: Huilong 迴龍

Content topic: `/waku/2/huilong/proto`
