### ISSUE TITLE
Waku v2: Implement Nim Node API

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-waku#78]
## Problem

Implement Node API documented here https://github.com/status-im/nim-waku/pull/77

Currently we have stubs (in the PR).

## Acceptance criteria

Following methods implemented and hooked up according to docs:

- [x] init
- [x] subscribe topic
- [x] publish topic and content

- [x] subscribe content
- [ ] unsubscribe topic and content
- [x] query

See linked issues below

- [x] tweak init signature

See https://github.com/status-im/nim-waku/issues/121 for merging calls context

**Comment by oskarth** [comment]
Re data -> Message field https://github.com/status-im/nim-waku/issues/92

**Comment by kdeme** [comment]
I currently do not really see why there is the need for both topic and content publish/subscribe/unsubscribe.

Topic here means libp2p pubsub topic. When subscribing for content, you will underneath automatically need to be subscribed on the used libp2p pubsub topic. And similarly for publishing.

**Comment by oskarth** [comment]
Because some deployments might have different tradeoffs when it comes to privacy and bw etc. They may choose not to rely on content filters, but only use it as a vanilla gossip sub. I don't expect the Status clients to use this mode. It is about providing options.

**Comment by kdeme** [comment]
Alright, but then it should be possible to provide an empty or no contentFilter. The point of my question was rather whether this is any need/reason to allow for selecting the PubSub topic at the node API?

**Comment by oskarth** [comment]
You might be right. If I understand you correctly, essentially this would mean making the topic publish/subscribe/unsubscribe methods private/implementation details?

**Comment by oskarth** [comment]
> then it should be possible to provide an empty or no contentFilter.

True and you might be right. If I understand you correctly, essentially this would mean making the topic publish/subscribe/unsubscribe methods private/implementation details?

>  to allow for selecting the PubSub topic at the node API?

I definitely think there should be. Specific deployments have different needs. So this would have to be a parameter if we go with a single publish/subscribe/unsubscribe call.

I also see we've had this conversation before :P https://github.com/status-im/nim-waku/issues/61 I think one difference since then is in terms of the req/resp domain being split with the recent three protocol split.

**Comment by kdeme** [comment]
> I also see we've had this conversation before :P

Yup, I realize that :-)

> I definitely think there should be. Specific deployments have different needs. So this would have to be a parameter if we go with a single publish/subscribe/unsubscribe call.

I think this would rather be something passed at `WakuRelay` init. And one would subscribe just once to the PubSub Topic (when initializing the WakuRelay), and unsubscribe when switching to light node functionality (stop `WakuRelay` and start using the req/resp domain). We can further discuss in the call today.

**Comment by oskarth** [comment]
Publish call merged now with WakuMessage. Updated in light of above issue https://github.com/status-im/nim-waku/issues/121

**Comment by oskarth** [comment]
Basic attempt at merging subscription and discussion thereof: https://github.com/status-im/nim-waku/pull/135#discussion_r483454948

Pausing this until we know exactly what we want, the current API calls works OK.

**Comment by oskarth** [comment]
@decanus please update here next step as well so we know what the state is.

Subscribe and Query done I believe (at least first cuts). Only unsubscribes missing, can be done separately. Think we can close this issue for now and revisit with more targeted specifics?

**Comment by oskarth** [comment]
@kdeme I believe we talked previously about the "toggle mode" issue. Is this something you'd want to write up?

Personally, I think we can make do with this for now, and then restart node when switching mode. Doing the switch at runtime seems a bit more complex to me and more like an advanced feature.

Anyway, will close this meta issue for now.
