### ISSUE TITLE
Release `nim-waku` v0.7

### ISSUE THREAD

**Issue by jm-clius** [status-im/nim-waku#808]
This issue tracks release `v0.7` of `nim-waku`. Several features, bugfixes and changes were added since release `v0.6`.
The main drivers for this release is:
- secure websocket support on the `prod` fleet
- addressing [performance issues](https://github.com/status-im/nim-waku/issues/736) on the `prod` fleet
- fixing [a long-standing persistent storage bug](https://github.com/status-im/nim-waku/issues/791) on `prod`

#### Before release

- [x] Merge https://github.com/status-im/nim-waku/pull/804
- [x] Merge https://github.com/status-im/nim-waku/pull/803
- [x] Merge https://github.com/status-im/nim-waku/pull/801
- [x] Merge https://github.com/status-im/nim-waku/pull/800
- [x] Investigate performance issues on fleet: https://github.com/status-im/nim-waku/issues/736
- [x] https://github.com/status-im/nim-waku/issues/805 (possible fix/improvement for #736)
- [ ] Perhaps: https://github.com/vacp2p/rfc/issues/441
- [x] update submodules
- [x] ensure `CHANGELOG` up to date
- [x] inform Waku v2 clients of changes and how they may be affected

#### For release

- [x] tag and perform GH release
- [x] add release notes, including summary of supported spec versions

#### After release

- [x] announce (on Twitter and other channels)
- [x] inform Waku v2 clients that release is done
- [x] deploy latest release to the `prod` fleet
- [x] deploy discoverable node list for `prod` fleet to DNS provider: https://github.com/status-im/nim-waku/issues/716
- [x] fix `prod` DBs: https://github.com/status-im/nim-waku/issues/806

### Further comments

@staheri14 @D4nte @oskarth - IMO a significant amount of critical things to get in before this release with another set of equally important tasks which can only be done after release (publishing DNS list, fixing the DB user versions, etc.) LMK what else you'd like to see included. The aim is to get to a relatively stable point where we can publish a docker image for user-run nodes ASAP. May be optimistic given uncertainty re investigations, but targeting ~2 weeks to be done.

**Comment by oskarth** [comment]
Sounds good to me!

Experimental RLN support would be great, but not a blocker

**Comment by jm-clius** [comment]
The release and all follow-up tasks have all now been concluded.
